# Generated by Django 2.0.6 on 2018-06-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0005_auto_20180627_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlist',
            name='images',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
