# Generated by Django 2.0.6 on 2018-06-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api_app', '0006_auto_20180627_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
