# Generated by Django 2.0.6 on 2018-06-28 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0007_doctorlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlist',
            name='location_coords',
            field=django.contrib.gis.db.models.fields.PointField(max_length=500, null=True, srid=4326),
        ),
    ]
