# Generated by Django 2.0.6 on 2018-06-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0008_doctorlist_location_coords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorlist',
            options={'verbose_name_plural': 'DoctorsList'},
        ),
    ]
