# Generated by Django 2.0.6 on 2018-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0009_auto_20180628_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlist',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='doctorlist',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
