# Generated by Django 2.0.6 on 2018-06-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0010_auto_20180629_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlist',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='doctorlist',
            name='longitude',
        ),
    ]
