# Generated by Django 2.0.6 on 2018-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0012_locationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
