# Generated by Django 2.0.6 on 2018-06-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0015_auto_20180629_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationModel',
        ),
    ]
