# Generated by Django 2.0.6 on 2018-07-03 05:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0016_delete_locationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlist',
            name='location_coords',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
